class Fibonacci
	def self.calculation(target)
		a = 1
		b = 2
		fibo_string=[a,b]
		loop do
			break if a > target || b > target
			a = a + b
			fibo_string << a if a < target
			b = b + a
			fibo_string << b if b < target			
		end
		fibo_string.delete_if{|i| i.odd?}.inject {|sum, n| sum + n } # inject details here: http://www.ruby-doc.org/core-1.9.3/Enumerable.html#method-i-inject
	end
end

puts "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed _________, find the sum of the even-valued terms."

puts "Insert Number Below:"
number = gets.chomp.to_i	#user imput converted to integer
puts "The sum is: #{Fibonacci.calculation(number)}"
